import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../components/Navbar';
import Countries from '../components/Countries';
import { useAppContext } from '../context/state';
import SearchBar from '../components/SearchBar';
import SortButton from '../components/SortButton';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import axios from 'axios';

export const getStaticProps = async () => {

  const res = await fetch('https://restcountries.com/v3.1/all')
  const countries = await res.json()

  return {
    props: {
      countries
    },
  }
}


export default function Home({ countries }) {
  
  const { darkMode } = useAppContext()
  const { continent, setContinent } = useAppContext()
  const { searching, setSearching } = useAppContext()
  const [sortList, setSortList] = useState(countries)
  
  
  
  useEffect(() => {
    if(continent != null && searching == "") {

      let continentList = countries.filter(country => country.region == continent)
      setSortList(continentList)
      setContinent(null)


    }  else if(searching != "") {

      axios.get(`https://restcountries.com/v3.1/name/${searching}`)
      .then(res => setSortList(res.data))
      .catch((error) => setSortList([]))
      setSearching("")

    }



  }, [continent, searching])
  
  const countriesJSX = sortList.map((country) => {
    return <Link href={`/${country.name.common}`} key={country.name.common}>
    <a className="w-[264px] h-[326px] rounded-md mx-auto my-10 flex flex-col justify-between bg-white drop-shadow-lg dark:bg-dark-blue-dark-mode desktop:m-[35px]">
      <Image 
          src={country.flags.png}
          width={264}
          height={160}
          alt={`${country.name.common} flag`}
      />
      <p className="my-2 mx-6 font-extrabold text-lg dark:text-white">{country.name.common}</p>
      <div className='mx-6 mb-10 dark:text-white'>
          <p className='font-semibold'>Population: <span className='font-light'>{country.population.toLocaleString("en-US")}</span></p>
          <p className='font-semibold'>Region: <span className='font-light'>{country.region}</span></p>
          <p className='font-semibold'>Capital: <span className='font-light'>{country.capital}</span></p>
      </div>
    </a>
  </Link>
  })

  return (
    <div className={darkMode ? 'dark' : 'light'}>
      <Head>
        <title>Where in the World ?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className='tablet:flex tablet:justify-between'>
        <SearchBar />
        <SortButton />
      </div>
      
      {/* // TODO: Ajouter le composant dynamic permettant d'afficher tous les pays de manières "Lazy" */}
      <main className='tablet:flex tablet:max-w-full tablet:flex-wrap desktop:mx-[50px] desktop:my-7'>
        {countriesJSX}
      </main>
      {/* // TODO : Essayer de faire en sorte que les pays soient dans un composant */}
      {/* <Countries /> */}
    </div>
  )
}
